spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/banking_application?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${db_username}
    password: ${db_password}

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true
        forex:
          api:
            key: ${FOREX_API_KEY:}
            url: ${FOREX_API_URL:}
            base: ${FOREX_API_BASE:}
            init-exchange-rates: true
        loans:
          api:
            baseUrl: ${LOANS_BASE_URL:http://localhost:8081}

  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # For MySQL 5
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # Cloudinary Properties
  # cloudinary:
  #   api-key:
  #   api-secret:
  #   cloud-name:

#  rest:
#    configuration: prod

  logging:
    level:
      org:
        springframework:
          security: DEBUG

